# 任务3 特征工程&特征选择(3天)

# 特征工程

#核心代码举例

# 统计特征
    #计算均值
    gp = train.groupby(by)[fea].mean()
    #计算中位数
    gp = train.groupby(by)[fea].median()
    #计算方差
    gp = train.groupby(by)[fea].std()
    #计算最大值
    gp = train.groupby(by)[fea].max()
    #计算最小值
    gp = train.groupby(by)[fea].min()
    #计算出现次数
    gp = train.groupby(by)[fea].size()
    

# groupby生成统计特征：mean,std
    # 按照communityName分组计算面积的均值和方差
    temp = data.groupby('communityName')['area'].agg({'com_area_mean': 'mean', 'com_area_std': 'std'})

# 特征拆分
    # 将houseType转为'Room'，'Hall'，'Bath'
    def Room(x):
        Room = int(x.split('室')[0])
        return Room
    def Hall(x):
        Hall = int(x.split("室")[1].split("厅")[0])
        return Hall
    def Bath(x):
        Bath = int(x.split("室")[1].split("厅")[1].split("卫")[0])
        return Bath

    data['Room'] = data['houseType'].apply(lambda x: Room(x))
    data['Hall'] = data['houseType'].apply(lambda x: Hall(x))
    data['Bath'] = data['houseType'].apply(lambda x: Bath(x))
    
#特征合并
    # 合并部分配套设施特征
    data['trainsportNum'] = 5 * data['subwayStationNum'] / data['subwayStationNum'].mean() + data['busStationNum'] / \
                                                                                             data[
                                                                                                 'busStationNum'].mean()

# 交叉生成特征:特征之间交叉+ - * / 
data['Room_Bath'] = (data['Bath']+1) / (data['Room']+1)


# 聚类特征
from sklearn.mixture import GaussianMixture  使用GaussianMixture做聚类特征
gmm = GaussianMixture(n_components=4, covariance_type='full', random_state=0)
gmm.fit_predict(data)
 
# 特征编码
from sklearn.preprocessing import LabelEncoder
data['communityName'] = LabelEncoder().fit_transform(data['communityName'])
from sklearn import preprocessing.OneHotEncoder
data['communityName'] = OneHotEncoder().fit_transform(data['communityName'])


# 过大量级值取log平滑（针对线性模型有效）
data[feature]=np.log1p(data[feature])

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import IsolationForest
pd.options.display.max_columns = None
from sklearn.model_selection import train_test_split

In [2]:
origin = pd.read_csv('数据集/train_data.csv')
train, test, Y_train, Y_test = train_test_split(origin, origin["tradeMoney"], test_size=0.3, random_state=30)
# target_train = train.pop('tradeMoney')
# target_test = test.pop('tradeMoney')

In [3]:
print(origin.shape)

(41440, 51)

In [4]:
train.head()

,ID,area,rentType,houseType,houseFloor,totalFloor,houseToward,houseDecoration,communityName,city,region,plate,buildYear,saleSecHouseNum,subwayStationNum,busStationNum,interSchoolNum,schoolNum,privateSchoolNum,hospitalNum,drugStoreNum,gymNum,bankNum,shopNum,parkNum,mallNum,superMarketNum,totalTradeMoney,totalTradeArea,tradeMeanPrice,tradeSecNum,totalNewTradeMoney,totalNewTradeArea,tradeNewMeanPrice,tradeNewNum,remainNewNum,supplyNewNum,supplyLandNum,supplyLandArea,tradeLandNum,tradeLandArea,landTotalPrice,landMeanPrice,totalWorkers,newWorkers,residentPopulation,pv,uv,lookNum,tradeTime,tradeMoney
36041,100010531,57.88,未知方式,1室1厅1卫,高,15,南,其他,XQ00706,SH,RG00002,BK00054,暂无信息,0,6,306,1,61,2,5,94,37,50,419,14,10,126,392130000,12589.57,31147.21154,158,26293744,751,35011.64314,5,214,0,0,0.0,0,0.0,0,0.0,8498,0,428071,64170.0,6665.0,0,2018/6/18,2650.0
1232,100147629,42.38,未知方式,2室0厅1卫,低,7,西北,其他,XQ03806,SH,RG00012,BK00012,1986,0,7,82,0,59,8,5,40,25,42,354,6,4,63,438650000,7612.89,57619.37976,113,23201066,240,96671.10833,2,59,0,0,0.0,0,0.0,0,0.0,120755,0,309216,10489.0,1328.0,0,2018/3/2,4000.0
14429,100150268,78.00,整租,2室2厅1卫,高,18,南,精装,XQ01723,SH,RG00004,BK00043,暂无信息,1,2,98,0,10,3,1,37,16,18,150,6,8,46,613340000,17786.21,34484.01880,199,1687918516,34610,48769.67686,301,407,371,0,0.0,0,0.0,0,0.0,253330,0,165159,30581.0,2704.0,0,2018/8/8,5000.0
6069,100306156,35.60,未知方式,1室0厅1卫,低,5,南,其他,XQ02684,SH,RG00007,BK00029,1957,15,0,27,3,24,9,5,11,6,27,65,4,2,15,488757600,9483.30,51538.76815,169,0,0,0.00000,0,0,0,0,0.0,0,0.0,0,0.0,49805,111,98604,293.0,58.0,0,2018/11/11,3550.0
14485,100149952,36.78,未知方式,1室1厅1卫,高,4,南,其他,XQ01355,SH,RG00003,BK00045,2003,0,5,824,3,99,9,11,174,88,119,824,24,19,299,1088280000,37696.24,28869.72282,422,274032611,6796,40322.63258,62,775,0,2,138730.8,0,0.0,0,0.0,46725,0,928198,147575.0,13354.0,0,2018/6/8,2000.0

In [5]:
test.head()

,ID,area,rentType,houseType,houseFloor,totalFloor,houseToward,houseDecoration,communityName,city,region,plate,buildYear,saleSecHouseNum,subwayStationNum,busStationNum,interSchoolNum,schoolNum,privateSchoolNum,hospitalNum,drugStoreNum,gymNum,bankNum,shopNum,parkNum,mallNum,superMarketNum,totalTradeMoney,totalTradeArea,tradeMeanPrice,tradeSecNum,totalNewTradeMoney,totalNewTradeArea,tradeNewMeanPrice,tradeNewNum,remainNewNum,supplyNewNum,supplyLandNum,supplyLandArea,tradeLandNum,tradeLandArea,landTotalPrice,landMeanPrice,totalWorkers,newWorkers,residentPopulation,pv,uv,lookNum,tradeTime,tradeMoney
31363,100035824,62.45,整租,2室1厅1卫,低,18,南,精装,XQ02282,SH,RG00005,BK00040,2010,0,7,138,2,41,24,0,67,43,35,224,7,6,75,141480000,4519.40,31305.04049,65,14982767,248,60414.38306,1,48,0,0,0.0,0,0.0,0,0.0,17401,0,319860,23515.0,2661.0,0,2018/3/9,5300.0
26208,100064898,44.29,未知方式,1室1厅1卫,中,6,南,其他,XQ02249,SH,RG00005,BK00039,1980,4,1,41,2,21,9,2,22,28,24,80,1,2,21,1040680000,21633.04,48106.04520,250,68461853,792,86441.73359,3,61,0,0,0.0,0,0.0,0,0.0,11209,0,134822,8431.0,1405.0,0,2018/9/2,3700.0
11590,100200789,100.00,未知方式,2室1厅1卫,低,7,南,毛坯,XQ01634,SH,RG00004,BK00042,暂无信息,0,13,441,1,62,8,9,145,84,91,671,30,16,159,109340000,3382.67,32323.57871,45,835783956,26501,31537.82710,259,2193,258,0,0.0,0,0.0,0,0.0,120140,0,589930,80164.0,5250.0,0,2018/2/28,2700.0
8479,100262036,41.00,未知方式,1室1厅1卫,中,15,南,其他,XQ01413,SH,RG00003,BK00046,2007,6,1,167,1,13,2,3,54,25,21,167,0,2,100,560700000,16001.07,35041.40661,149,368507053,7965,46265.79448,58,142,0,0,0.0,0,0.0,0,0.0,19615,0,274232,17911.0,4094.0,0,2018/9/10,3700.0
3401,100036819,144.50,未知方式,3室2厅2卫,中,11,南北,其他,XQ01033,SH,RG00002,BK00056,2002,0,14,258,0,98,13,5,88,52,75,341,11,7,130,1905570000,35849.63,53154.52349,443,0,0,0.00000,0,82,0,0,0.0,0,0.0,0,0.0,388879,0,491767,39739.0,6001.0,0,2018/7/31,7500.0

In [6]:
target_train = train.pop('tradeMoney')
target_test = test.pop('tradeMoney')

In [7]:
# # clean data
# def IF_drop(data):
#     # 孤立森林模型
#     IForest = IsolationForest(contamination=0.01)
#     IForest.fit(data["tradeMoney"].values.reshape(-1,1))
#     y_pred = IForest.predict(data["tradeMoney"].values.reshape(-1,1))
#     # 训练孤立点森林模型，然后预测孤立点，筛选出他们的索引并把这些行删除掉
#     drop_index = data.loc[y_pred==-1].index
#     data.drop(drop_index,inplace=True)
#     return data

# train = IF_drop(train)

In [8]:
def preprocessingData(data):
    # 填充缺失值
    # 有两种缺失值：-- 和 未知方式 
    # 把 -- 转换为 未知方式 然后使用 labelEncoder 编码
    data['rentType'][data['rentType'] == '--'] = '未知方式'
    
    # 转换object类型数据
    columns = ['rentType','communityName', 'houseFloor', 'houseToward', 'houseDecoration',  'region', 'plate']
    
    for feature in columns:
        le = LabelEncoder()
        data[feature] = le.fit_transform(data[feature])
#         print(le.classes_)

    # 将buildYear列转换为整型数据
    # 缺失值是 暂无信息
    # 取非缺失值，计算buildYear的众数： 1994
    # buildYearmean.iloc[0, 0] 是取这个serise的值
    buildYearmean = pd.DataFrame(data[data['buildYear'] != '暂无信息']['buildYear'].mode())
    # data[data['buildYear'] != '暂无信息']['buildYear'] 这种方式也可以赋值
    data.loc[data[data['buildYear'] == '暂无信息'].index, 'buildYear'] = buildYearmean.iloc[0, 0]
    # 改变buildYear类型 buildYear最开始是object类型，现在需要转换为int类型
    data['buildYear'] = data['buildYear'].astype('int')

    # 处理pv和uv的空值
    # 使用平均值填充
    data['pv'].fillna(data['pv'].mean(), inplace=True)
    data['uv'].fillna(data['uv'].mean(), inplace=True)
    # pv和uv是float类型，根据实际经验这里转为int类型
    data['pv'] = data['pv'].astype('int')
    data['uv'] = data['uv'].astype('int')

    # 分割交易时间tradeTime
    # 没有缺失值，可以直接处理
    # 全部是2008年所以不用分割年
    # 分割出月和日即可
    def month(x):
        month = int(x.split('/')[1])
        return month
    def day(x):
        day = int(x.split('/')[2])
        return day
    data['month'] = data['tradeTime'].apply(lambda x: month(x))
    data['day'] = data['tradeTime'].apply(lambda x: day(x))
    
    # 去掉部分特征
    data.drop('city', axis=1, inplace=True)
#     data.drop('tradeTime', axis=1, inplace=True)
    data.drop('ID', axis=1, inplace=True)
    return data

train = preprocessingData(train)
test = preprocessingData(test)

In [9]:
# train['Type'] = 'Train'
# test['Type'] = 'Test'
# data_all = pd.concat([train, test], ignore_index=True)

## 特征合并

In [10]:
def newfeature(data):

    # 将x室x厅拆分
    # 将houseType转为'Room'，'Hall'，'Bath'
    def Room(x):
        Room = int(x.split('室')[0])
        return Room
    def Hall(x):
        Hall = int(x.split("室")[1].split("厅")[0])
        return Hall
    def Bath(x):
        Bath = int(x.split("室")[1].split("厅")[1].split("卫")[0])
        return Bath

    data['Room'] = data['houseType'].apply(lambda x: Room(x))
    data['Hall'] = data['houseType'].apply(lambda x: Hall(x))
    data['Bath'] = data['houseType'].apply(lambda x: Bath(x))
    data['Room_Bath'] = (data['Bath']+1) / (data['Room']+1)
    
    # 根据面积和房间的数量填充租房类型（未知方式的真实类型）
    # 填充租房类型
    data.loc[(data['rentType'] == '未知方式') & (data['Room'] <= 1), 'rentType'] = '整租'
    # print(data.loc[(data['rentType']=='未知方式')&(data['Room_Bath']>1),'rentType'])
    data.loc[(data['rentType'] == '未知方式') & (data['Room_Bath'] > 1), 'rentType'] = '合租'
    data.loc[(data['rentType'] == '未知方式') & (data['Room'] > 1) & (data['area'] < 50), 'rentType'] = '合租'
    data.loc[(data['rentType'] == '未知方式') & (data['area'] / data['Room'] < 20), 'rentType'] = '合租'
    # data.loc[(data['rentType']=='未知方式')&(data['area']>60),'rentType']='合租'
    data.loc[(data['rentType'] == '未知方式') & (data['area'] <= 50) & (data['Room'] == 2), 'rentType'] = '合租'
    data.loc[(data['rentType'] == '未知方式') & (data['area'] > 60) & (data['Room'] == 2), 'rentType'] = '整租'
    data.loc[(data['rentType'] == '未知方式') & (data['area'] <= 60) & (data['Room'] == 3), 'rentType'] = '合租'
    data.loc[(data['rentType'] == '未知方式') & (data['area'] > 60) & (data['Room'] == 3), 'rentType'] = '整租'
    data.loc[(data['rentType'] == '未知方式') & (data['area'] >= 100) & (data['Room'] > 3), 'rentType'] = '整租'
    
    # 拆分成交日期，单独构造成交月份的字段
    # data.drop('Room_Bath', axis=1, inplace=True)
    # 提升0.0001
    def month(x):
        month = int(x.split('/')[1])
        return month
    # def day(x):
    #     day = int(x.split('/')[2])
    #     return day
    # 结果变差

    # 分割交易时间
    # data['year']=data['tradeTime'].apply(lambda x:year(x))
    data['month'] = data['tradeTime'].apply(lambda x: month(x))
    # data['day'] = data['tradeTime'].apply(lambda x: day(x))# 结果变差
    #     data['pv/uv'] = data['pv'] / data['uv']
    #     data['房间总数'] = data['室'] + data['厅'] + data['卫']

    # 合并部分配套设施特征
    data['trainsportNum'] = 5 * data['subwayStationNum'] / data['subwayStationNum'].mean() + data['busStationNum'] / \
                                                                                             data[
                                                                                                 'busStationNum'].mean()
    data['all_SchoolNum'] = 2 * data['interSchoolNum'] / data['interSchoolNum'].mean() + data['schoolNum'] / data[
        'schoolNum'].mean() \
                            + data['privateSchoolNum'] / data['privateSchoolNum'].mean()
    data['all_hospitalNum'] = 2 * data['hospitalNum'] / data['hospitalNum'].mean() + \
                              data['drugStoreNum'] / data['drugStoreNum'].mean()
    data['all_mall'] = data['mallNum'] / data['mallNum'].mean() + \
                       data['superMarketNum'] / data['superMarketNum'].mean()
    data['otherNum'] = data['gymNum'] / data['gymNum'].mean() + data['bankNum'] / data['bankNum'].mean() + \
                       data['shopNum'] / data['shopNum'].mean() + 2 * data['parkNum'] / data['parkNum'].mean()

    data.drop(['subwayStationNum', 'busStationNum',
               'interSchoolNum', 'schoolNum', 'privateSchoolNum',
               'hospitalNum', 'drugStoreNum', 'mallNum', 'superMarketNum', 'gymNum', 'bankNum', 'shopNum', 'parkNum'],
              axis=1, inplace=True)
    # 提升0.0005
    
#     data['houseType_1sumcsu']=data['Bath'].map(lambda x:str(x))+data['month'].map(lambda x:str(x))
#     data['houseType_2sumcsu']=data['Bath'].map(lambda x:str(x))+data['communityName']
#     data['houseType_3sumcsu']=data['Bath'].map(lambda x:str(x))+data['plate']
    
    data.drop('houseType', axis=1, inplace=True)
    data.drop('tradeTime', axis=1, inplace=True)
    
    data["area"] = data["area"].astype(int)


    # categorical_feats = ['rentType', 'houseFloor', 'houseToward', 'houseDecoration', 'communityName','region', 'plate']
    categorical_feats = ['rentType', 'houseFloor', 'houseToward', 'houseDecoration',  'region', 'plate','cluster']

    return data, categorical_feats

In [11]:
train, cate_df_all = newfeature(train)
test, cate_df_all = newfeature(test)

In [12]:
train.head()

,area,rentType,houseFloor,totalFloor,houseToward,houseDecoration,communityName,region,plate,buildYear,saleSecHouseNum,totalTradeMoney,totalTradeArea,tradeMeanPrice,tradeSecNum,totalNewTradeMoney,totalNewTradeArea,tradeNewMeanPrice,tradeNewNum,remainNewNum,supplyNewNum,supplyLandNum,supplyLandArea,tradeLandNum,tradeLandArea,landTotalPrice,landMeanPrice,totalWorkers,newWorkers,residentPopulation,pv,uv,lookNum,month,day,Room,Hall,Bath,Room_Bath,trainsportNum,all_SchoolNum,all_hospitalNum,all_mall,otherNum
36041,57,2,2,15,4,0,646,1,53,1994,0,392130000,12589.57,31147.21154,158,26293744,751,35011.64314,5,214,0,0,0.0,0,0.0,0,0.0,8498,0,428071,64170,6665,0,6,18,1,1,1,1.000000,6.861430,2.914163,3.955609,3.118232,7.035898
1232,42,2,1,7,8,0,3470,11,11,1986,0,438650000,7612.89,57619.37976,113,23201066,240,96671.10833,2,59,0,0,0.0,0,0.0,0,0.0,120755,0,309216,10489,1328,0,3,2,2,0,1,0.666667,6.533145,2.499231,3.019493,1.399270,4.335986
14429,78,1,2,18,4,3,1595,3,42,1994,1,613340000,17786.21,34484.01880,199,1687918516,34610,48769.67686,301,407,371,0,0.0,0,0.0,0,0.0,253330,0,165159,30581,2704,0,8,8,2,2,1,0.666667,2.265734,0.685633,1.106628,1.833608,2.839831
6069,35,2,1,5,4,0,2466,6,28,1957,15,488757600,9483.30,51538.76815,169,0,0,0.00000,0,0,0,0,0.0,0,0.0,0,0.0,49805,111,98604,293,58,0,11,11,1,0,1,1.000000,0.144510,5.921589,2.516764,0.500618,1.940400
14485,36,2,2,4,4,0,1255,2,44,2003,0,1088280000,37696.24,28869.72282,422,274032611,6796,40322.63258,62,775,0,2,138730.8,0,0.0,0,0.0,46725,0,928198,147575,13354,0,6,8,1,1,1,1.000000,8.763263,7.477743,8.133736,6.643515,13.817228

In [13]:
cate_df_all

['rentType',
 'houseFloor',
 'houseToward',
 'houseDecoration',
 'region',
 'plate',
 'cluster']

## 计算统计特征

In [14]:
#计算统计特征
# 统计不同行数据指定字段该特征值在所有数据中有多少条
def featureCount(train,test):
    train['data_type'] = 0
    test['data_type'] = 1
    data = pd.concat([train, test], axis=0, join='outer')
    def feature_count(data, features=[]):
        new_feature = 'count'
        for i in features:
            new_feature += '_' + i
        temp = data.groupby(features).size().reset_index().rename(columns={0: new_feature})
        data = data.merge(temp, 'left', on=features)
        return data

    data = feature_count(data, ['communityName'])  # 统计相同小区出现了多少次
    data = feature_count(data, ['buildYear'])  # 统计相同的建筑年限出现了多少次
    data = feature_count(data, ['totalFloor'])  # 统计相同的总楼层出现的次数
    data = feature_count(data, ['communityName', 'totalFloor'])  # 不同小区的总楼层
    data = feature_count(data, ['communityName', 'newWorkers'])  # 不同的小区的当月流入人口
    data = feature_count(data, ['communityName', 'totalTradeMoney'])  # 不同小区的当月二手房成交总额次数
    new_train = data[data['data_type'] == 0]
    new_test = data[data['data_type'] == 1]
    new_train.drop('data_type', axis=1, inplace=True)
    new_test.drop(['data_type'], axis=1, inplace=True)
    return new_train, new_test
    
train, test = featureCount(train, test)

In [15]:
train.groupby("communityName").size()[:5]

communityName
0    1
1    1
2    1
3    1
4    8
dtype: int64

In [16]:
train.groupby(['communityName', 'totalTradeMoney']).size()[:5]

communityName  totalTradeMoney
0              339655896          1
1              416910000          1
2              416910000          1
3              509150000          1
4              416910000          1
dtype: int64

In [17]:
train.head()

,area,rentType,houseFloor,totalFloor,houseToward,houseDecoration,communityName,region,plate,buildYear,saleSecHouseNum,totalTradeMoney,totalTradeArea,tradeMeanPrice,tradeSecNum,totalNewTradeMoney,totalNewTradeArea,tradeNewMeanPrice,tradeNewNum,remainNewNum,supplyNewNum,supplyLandNum,supplyLandArea,tradeLandNum,tradeLandArea,landTotalPrice,landMeanPrice,totalWorkers,newWorkers,residentPopulation,pv,uv,lookNum,month,day,Room,Hall,Bath,Room_Bath,trainsportNum,all_SchoolNum,all_hospitalNum,all_mall,otherNum,count_communityName,count_buildYear,count_totalFloor,count_communityName_totalFloor,count_communityName_newWorkers,count_communityName_totalTradeMoney
0,57,2,2,15,4,0,646,1,53,1994,0,392130000,12589.57,31147.21154,158,26293744,751,35011.64314,5,214,0,0,0.0,0,0.0,0,0.0,8498,0,428071,64170,6665,0,6,18,1,1,1,1.000000,6.861430,2.914163,3.955609,3.118232,7.035898,15,5659,809,14,10,1
1,42,2,1,7,8,0,3470,11,11,1986,0,438650000,7612.89,57619.37976,113,23201066,240,96671.10833,2,59,0,0,0.0,0,0.0,0,0.0,120755,0,309216,10489,1328,0,3,2,2,0,1,0.666667,6.533145,2.499231,3.019493,1.399270,4.335986,21,320,1362,21,19,4
2,78,1,2,18,4,3,1595,3,42,1994,1,613340000,17786.21,34484.01880,199,1687918516,34610,48769.67686,301,407,371,0,0.0,0,0.0,0,0.0,253330,0,165159,30581,2704,0,8,8,2,2,1,0.666667,2.265734,0.685633,1.106628,1.833608,2.839831,15,5659,3553,11,11,1
3,35,2,1,5,4,0,2466,6,28,1957,15,488757600,9483.30,51538.76815,169,0,0,0.00000,0,0,0,0,0.0,0,0.0,0,0.0,49805,111,98604,293,58,0,11,11,1,0,1,1.000000,0.144510,5.921589,2.516764,0.500618,1.940400,56,227,2730,48,5,5
4,36,2,2,4,4,0,1255,2,44,2003,0,1088280000,37696.24,28869.72282,422,274032611,6796,40322.63258,62,775,0,2,138730.8,0,0.0,0,0.0,46725,0,928198,147575,13354,0,6,8,1,1,1,1.000000,8.763263,7.477743,8.133736,6.643515,13.817228,8,1156,486,3,7,1

## groupby方法生成统计特征

In [18]:
#groupby生成统计特征：mean,std等
# 为部分特征新增一些统计特征
def gourpby(train,test):
    train['data_type'] = 0
    test['data_type'] = 1
    data = pd.concat([train, test], axis=0, join='outer')
    
    # 数字编码
    columns = ['rentType', 'houseFloor', 'houseToward', 'houseDecoration', 'communityName', 'region', 'plate']
    for feature in columns:
        data[feature] = LabelEncoder().fit_transform(data[feature])
    
    # 不同小区房源面积的平均值和标准差
    temp = data.groupby('communityName')['area'].agg({'com_area_mean': 'mean', 'com_area_std': 'std'})
    # nan填充0
    temp.fillna(0, inplace=True)
    data = data.merge(temp, on='communityName', how='left')
    
    # 计算平均面积出租价格
    data['price_per_area'] = data.tradeMeanPrice / data.area * 100
    
    # 小区的面积价格的平均值和标准差
    temp = data.groupby('communityName')['price_per_area'].agg(
        {'comm_price_mean': 'mean', 'comm_price_std': 'std'})
    temp.fillna(0, inplace=True)
    data = data.merge(temp, on='communityName', how='left')
    
    # 区域板块的面积价格的平均值和标准差
    temp = data.groupby('plate')['price_per_area'].agg(
        {'plate_price_mean': 'mean', 'plate_price_std': 'std'})
    temp.fillna(0, inplace=True)
    data = data.merge(temp, on='plate', how='left')
    data.drop('price_per_area', axis=1, inplace=True)
    
    # 区域-面积 => 平均值 标准差
    temp = data.groupby('plate')['area'].agg({'plate_area_mean': 'mean', 'plate_area_std': 'std'})
    temp.fillna(0, inplace=True)
    data = data.merge(temp, on='plate', how='left')
    
    # 区域 建筑年份
    temp = data.groupby(['plate'])['buildYear'].agg({'plate_year_mean': 'mean', 'plate_year_std': 'std'})
    data = data.merge(temp, on='plate', how='left')
    data.plate_year_mean = data.plate_year_mean.astype('int')
    data['comm_plate_year_diff'] = data.buildYear - data.plate_year_mean  # 年份 - 平均年份
    data.drop('plate_year_mean', axis=1, inplace=True)
    
    # 区域——交通特征
    temp = data.groupby('plate')['trainsportNum'].agg('sum').reset_index(name='plate_trainsportNum')
    data = data.merge(temp, on='plate', how='left')
    temp = data.groupby(['communityName', 'plate'])['trainsportNum'].agg('sum').reset_index(name='com_trainsportNum')
    data = data.merge(temp, on=['communityName', 'plate'], how='left')
    data['trainsportNum_ratio'] = list(map(lambda x, y: round(x / y, 3) if y != 0 else -1,
                                           data['com_trainsportNum'], data['plate_trainsportNum']))
    data = data.drop(['com_trainsportNum', 'plate_trainsportNum'], axis=1)

    # 区域 学校数量 总数
    temp = data.groupby('plate')['all_SchoolNum'].agg('sum').reset_index(name='plate_all_SchoolNum')
    data = data.merge(temp, on='plate', how='left')
    temp = data.groupby(['communityName', 'plate'])['all_SchoolNum'].agg('sum').reset_index(name='com_all_SchoolNum')
    data = data.merge(temp, on=['communityName', 'plate'], how='left')
    data = data.drop(['com_all_SchoolNum', 'plate_all_SchoolNum'], axis=1)
    
    # 小区-区域 总数
    temp = data.groupby(['communityName', 'plate'])['all_mall'].agg('sum').reset_index(name='com_all_mall')
    data = data.merge(temp, on=['communityName', 'plate'], how='left')
    
    # 区域 其他配套特征 总数
    temp = data.groupby('plate')['otherNum'].agg('sum').reset_index(name='plate_otherNum')
    data = data.merge(temp, on='plate', how='left')
    temp = data.groupby(['communityName', 'plate'])['otherNum'].agg('sum').reset_index(name='com_otherNum')
    data = data.merge(temp, on=['communityName', 'plate'], how='left')
    data['other_ratio'] = list(map(lambda x, y: round(x / y, 3) if y != 0 else -1,
                                   data['com_otherNum'], data['plate_otherNum']))
    data = data.drop(['com_otherNum', 'plate_otherNum'], axis=1)
    
    # 月份小区成交
    temp = data.groupby(['month', 'communityName']).size().reset_index(name='communityName_saleNum')
    data = data.merge(temp, on=['month', 'communityName'], how='left')
    temp = data.groupby(['month', 'plate']).size().reset_index(name='plate_saleNum')
    data = data.merge(temp, on=['month', 'plate'], how='left')
    
    # 成交比例
    data['sale_ratio'] = round((data.communityName_saleNum + 1) / (data.plate_saleNum + 1), 3)
    data['sale_newworker_differ'] = 3 * data.plate_saleNum - data.newWorkers
    data.drop(['communityName_saleNum', 'plate_saleNum'], axis=1, inplace=True)

    new_train = data[data['data_type'] == 0]
    new_test = data[data['data_type'] == 1]
    new_train.drop('data_type', axis=1, inplace=True)
    new_test.drop(['data_type'], axis=1, inplace=True)
    return new_train, new_test

train, test = gourpby(train, test)

In [19]:
train.head()

,area,rentType,houseFloor,totalFloor,houseToward,houseDecoration,communityName,region,plate,buildYear,saleSecHouseNum,totalTradeMoney,totalTradeArea,tradeMeanPrice,tradeSecNum,totalNewTradeMoney,totalNewTradeArea,tradeNewMeanPrice,tradeNewNum,remainNewNum,supplyNewNum,supplyLandNum,supplyLandArea,tradeLandNum,tradeLandArea,landTotalPrice,landMeanPrice,totalWorkers,newWorkers,residentPopulation,pv,uv,lookNum,month,day,Room,Hall,Bath,Room_Bath,trainsportNum,all_SchoolNum,all_hospitalNum,all_mall,otherNum,count_communityName,count_buildYear,count_totalFloor,count_communityName_totalFloor,count_communityName_newWorkers,count_communityName_totalTradeMoney,com_area_mean,com_area_std,comm_price_mean,comm_price_std,plate_price_mean,plate_price_std,plate_area_mean,plate_area_std,plate_year_std,comm_plate_year_diff,trainsportNum_ratio,com_all_mall,other_ratio,sale_ratio,sale_newworker_differ
0,57,2,2,15,4,0,646,1,53,1994,0,392130000,12589.57,31147.21154,158,26293744,751,35011.64314,5,214,0,0,0.0,0,0.0,0,0.0,8498,0,428071,64170,6665,0,6,18,1,1,1,1.000000,6.861430,2.914163,3.955609,3.118232,7.035898,15,5659,809,14,10,1,57.666667,8.005950,56011.618848,11432.901072,95866.315739,103261.303345,67.563758,87.878800,8.720308,-6,0.009,43.655253,0.012,0.014,429
1,42,2,1,7,8,0,3470,11,11,1986,0,438650000,7612.89,57619.37976,113,23201066,240,96671.10833,2,59,0,0,0.0,0,0.0,0,0.0,120755,0,309216,10489,1328,0,3,2,2,0,1,0.666667,6.533145,2.499231,3.019493,1.399270,4.335986,21,320,1362,21,19,4,39.238095,7.974364,140701.447242,25959.585233,154231.435167,144059.477704,53.939891,33.509477,14.759094,-3,0.047,29.384662,0.038,0.045,333
2,78,1,2,18,4,3,1595,3,42,1994,1,613340000,17786.21,34484.01880,199,1687918516,34610,48769.67686,301,407,371,0,0.0,0,0.0,0,0.0,253330,0,165159,30581,2704,0,8,8,2,2,1,0.666667,2.265734,0.685633,1.106628,1.833608,2.839831,15,5659,3553,11,11,1,72.866667,23.191337,64715.839564,83080.341652,74449.615731,83069.250127,74.935159,42.805242,9.095648,-12,0.016,20.169689,0.016,0.031,189
3,35,2,1,5,4,0,2466,6,28,1957,15,488757600,9483.30,51538.76815,169,0,0,0.00000,0,0,0,0,0.0,0,0.0,0,0.0,49805,111,98604,293,58,0,11,11,1,0,1,1.000000,0.144510,5.921589,2.516764,0.500618,1.940400,56,227,2730,48,5,5,35.839286,18.444784,169607.758678,78663.619452,142872.849542,97885.206437,46.166352,24.522229,14.789971,-20,0.028,27.533977,0.102,0.154,3
4,36,2,2,4,4,0,1255,2,44,2003,0,1088280000,37696.24,28869.72282,422,274032611,6796,40322.63258,62,775,0,2,138730.8,0,0.0,0,0.0,46725,0,928198,147575,13354,0,6,8,1,1,1,1.000000,8.763263,7.477743,8.133736,6.643515,13.817228,8,1156,486,3,7,1,56.250000,50.609852,104614.815020,88372.684692,77186.781252,117756.951718,77.491443,52.280512,7.267132,-1,0.005,46.504606,0.005,0.013,474

## 聚类方法

In [20]:
#聚类
# 新增聚类算法计算的数据列
def cluster(train,test):
    from sklearn.mixture import GaussianMixture

    train['data_type'] = 0
    test['data_type'] = 1
    data = pd.concat([train, test], axis=0, join='outer')
    col = ['totalFloor',
           'houseDecoration', 'communityName', 'region', 'plate', 'buildYear',

           'tradeMeanPrice', 'tradeSecNum', 'totalNewTradeMoney',
           'totalNewTradeArea', 'tradeNewMeanPrice', 'tradeNewNum', 'remainNewNum',

           'landTotalPrice', 'landMeanPrice', 'totalWorkers',
           'newWorkers', 'residentPopulation', 'lookNum',
           'trainsportNum',
           'all_SchoolNum', 'all_hospitalNum', 'all_mall', 'otherNum']

    # EM
    gmm = GaussianMixture(n_components=3, covariance_type='full', random_state=0)
    data['cluster']= pd.DataFrame(gmm.fit_predict(data[col]))


    col1 = ['totalFloor','houseDecoration', 'communityName', 'region', 'plate', 'buildYear']
    col2 = ['tradeMeanPrice', 'tradeSecNum', 'totalNewTradeMoney',
            'totalNewTradeArea', 'tradeNewMeanPrice', 'tradeNewNum', 'remainNewNum',
            'landTotalPrice', 'landMeanPrice', 'totalWorkers',
            'newWorkers', 'residentPopulation', 'lookNum',
            'trainsportNum',
            'all_SchoolNum', 'all_hospitalNum', 'all_mall', 'otherNum']
    for feature1 in col1:
        for feature2 in col2:
        
            temp = data.groupby(['cluster',feature1])[feature2].agg('mean').reset_index(name=feature2+'_'+feature1+'_cluster_mean')
            temp.fillna(0, inplace=True)
       
            data = data.merge(temp, on=['cluster', feature1], how='left')
    
   
    new_train = data[data['data_type'] == 0]
    new_test = data[data['data_type'] == 1]
    new_train.drop('data_type', axis=1, inplace=True)
    new_test.drop(['data_type'], axis=1, inplace=True)
    
    return new_train, new_test

train, test = cluster(train, test)

In [21]:
train.head()

,area,rentType,houseFloor,totalFloor,houseToward,houseDecoration,communityName,region,plate,buildYear,saleSecHouseNum,totalTradeMoney,totalTradeArea,tradeMeanPrice,tradeSecNum,totalNewTradeMoney,totalNewTradeArea,tradeNewMeanPrice,tradeNewNum,remainNewNum,supplyNewNum,supplyLandNum,supplyLandArea,tradeLandNum,tradeLandArea,landTotalPrice,landMeanPrice,totalWorkers,newWorkers,residentPopulation,pv,uv,lookNum,month,day,Room,Hall,Bath,Room_Bath,trainsportNum,all_SchoolNum,all_hospitalNum,all_mall,otherNum,count_communityName,count_buildYear,count_totalFloor,count_communityName_totalFloor,count_communityName_newWorkers,count_communityName_totalTradeMoney,com_area_mean,com_area_std,comm_price_mean,comm_price_std,plate_price_mean,plate_price_std,plate_area_mean,plate_area_std,plate_year_std,comm_plate_year_diff,trainsportNum_ratio,com_all_mall,other_ratio,sale_ratio,sale_newworker_differ,cluster,tradeMeanPrice_totalFloor_cluster_mean,tradeSecNum_totalFloor_cluster_mean,totalNewTradeMoney_totalFloor_cluster_mean,totalNewTradeArea_totalFloor_cluster_mean,tradeNewMeanPrice_totalFloor_cluster_mean,tradeNewNum_totalFloor_cluster_mean,remainNewNum_totalFloor_cluster_mean,landTotalPrice_totalFloor_cluster_mean,landMeanPrice_totalFloor_cluster_mean,totalWorkers_totalFloor_cluster_mean,newWorkers_totalFloor_cluster_mean,residentPopulation_totalFloor_cluster_mean,lookNum_totalFloor_cluster_mean,trainsportNum_totalFloor_cluster_mean,all_SchoolNum_totalFloor_cluster_mean,all_hospitalNum_totalFloor_cluster_mean,all_mall_totalFloor_cluster_mean,otherNum_totalFloor_cluster_mean,tradeMeanPrice_houseDecoration_cluster_mean,tradeSecNum_houseDecoration_cluster_mean,totalNewTradeMoney_houseDecoration_cluster_mean,totalNewTradeArea_houseDecoration_cluster_mean,tradeNewMeanPrice_houseDecoration_cluster_mean,tradeNewNum_houseDecoration_cluster_mean,remainNewNum_houseDecoration_cluster_mean,landTotalPrice_houseDecoration_cluster_mean,landMeanPrice_houseDecoration_cluster_mean,totalWorkers_houseDecoration_cluster_mean,newWorkers_houseDecoration_cluster_mean,residentPopulation_houseDecoration_cluster_mean,lookNum_houseDecoration_cluster_mean,trainsportNum_houseDecoration_cluster_mean,all_SchoolNum_houseDecoration_cluster_mean,all_hospitalNum_houseDecoration_cluster_mean,all_mall_houseDecoration_cluster_mean,otherNum_houseDecoration_cluster_mean,tradeMeanPrice_communityName_cluster_mean,tradeSecNum_communityName_cluster_mean,totalNewTradeMoney_communityName_cluster_mean,totalNewTradeArea_communityName_cluster_mean,tradeNewMeanPrice_communityName_cluster_mean,tradeNewNum_communityName_cluster_mean,remainNewNum_communityName_cluster_mean,landTotalPrice_communityName_cluster_mean,landMeanPrice_communityName_cluster_mean,totalWorkers_communityName_cluster_mean,newWorkers_communityName_cluster_mean,residentPopulation_communityName_cluster_mean,lookNum_communityName_cluster_mean,trainsportNum_communityName_cluster_mean,all_SchoolNum_communityName_cluster_mean,all_hospitalNum_communityName_cluster_mean,all_mall_communityName_cluster_mean,otherNum_communityName_cluster_mean,tradeMeanPrice_region_cluster_mean,tradeSecNum_region_cluster_mean,totalNewTradeMoney_region_cluster_mean,totalNewTradeArea_region_cluster_mean,tradeNewMeanPrice_region_cluster_mean,tradeNewNum_region_cluster_mean,remainNewNum_region_cluster_mean,landTotalPrice_region_cluster_mean,landMeanPrice_region_cluster_mean,totalWorkers_region_cluster_mean,newWorkers_region_cluster_mean,residentPopulation_region_cluster_mean,lookNum_region_cluster_mean,trainsportNum_region_cluster_mean,all_SchoolNum_region_cluster_mean,all_hospitalNum_region_cluster_mean,all_mall_region_cluster_mean,otherNum_region_cluster_mean,tradeMeanPrice_plate_cluster_mean,tradeSecNum_plate_cluster_mean,totalNewTradeMoney_plate_cluster_mean,totalNewTradeArea_plate_cluster_mean,tradeNewMeanPrice_plate_cluster_mean,tradeNewNum_plate_cluster_mean,remainNewNum_plate_cluster_mean,landTotalPrice_plate_cluster_mean,landMeanPrice_plate_cluster_mean,totalWorkers_plate_cluster_mean,newWorkers_plate_cluster_mean,residentPopulation_plate_cluster_mean,lookNum_plate_cluster_mean,trainsportNum_plate_cluster_mean,all_SchoolNum_plate_cluster_mean,all_hospitalNum_plate_cluster_mean,all_mall_plate_cluster_mean,otherNum_plate_cluster_mean,tradeMeanPrice_buildYear_cluster_mean,tradeSecNum_buildYear_cluster_mean,totalNewTradeMoney_buildYear_cluster_mean,totalNewTradeArea_buildYear_cluster_mean,tradeNewMeanPrice_buildYear_cluster_mean,tradeNewNum_buildYear_cluster_mean,remainNewNum_buildYear_cluster_mean,landTotalPrice_buildYear_cluster_mean,landMeanPrice_buildYear_cluster_mean,totalWorkers_buildYear_cluster_mean,newWorkers_buildYear_cluster_mean,residentPopulation_buildYear_cluster_mean,lookNum_buildYear_cluster_mean,trainsportNum_buildYear_cluster_mean,all_SchoolNum_buildYear_cluster_mean,all_hospitalNum_buildYear_cluster_mean,all_mall_buildYear_cluster_mean,otherNum_buildYear_cluster_mean
0,57,2,2,15,4,0,646,1,53,1994,0,392130000,12589.57,31147.21154,158,26293744,751,35011.64314,5,214,0,0,0.0,0,0.0,0,0.0,8498,0,428071,64170,6665,0,6,18,1,1,1,1.000000,6.861430,2.914163,3.955609,3.118232,7.035898,15,5659,809,14,10,1,57.666667,8.005950,56011.618848,11432.901072,95866.315739,103261.303345,67.563758,87.878800,8.720308,-6,0.009,43.655253,0.012,0.014,429,0,37234.390317,232.448845,2.134405e+08,4719.924092,38813.883094,41.143564,305.674917,3.745285e+07,265.775476,77849.013201,0.000000,330429.646865,0.000000,5.420387,3.315204,3.106066,2.327820,5.084342,40725.102969,229.518102,1.940921e+08,3806.600763,44245.116035,31.333564,271.877668,2.935649e+07,277.134168,78607.926551,0.000000,287437.223218,0.000000,5.608225,4.222785,2.883093,1.945022,4.747559,31079.504539,173.800000,3.818973e+07,1001.900000,35419.551532,4.100000,217.400000,0.000000e+00,0.000000,8498.000000,0.000000,428071.000000,0.000000,6.861430,2.914163,3.955609,3.118232,7.035898,41476.021283,321.679504,1.724097e+08,2949.490126,62580.585009,22.496382,216.609837,2.676943e+07,122.363175,151335.517601,0.000000,344045.843493,0.000000,9.273148,4.502851,3.550913,2.196679,6.243596,34773.122085,193.143013,1.158908e+08,2217.561135,44129.109313,14.838428,280.707424,0.000000e+00,0.000000,7763.432314,0.000000,406501.259825,0.000000,7.489401,2.629209,3.956709,2.870786,6.609019,38386.178484,215.547458,2.051141e+08,4220.866016,43980.696790,33.438267,314.098923,3.084462e+07,317.416683,57279.348109,0.000000,280336.653143,0.000000,5.524240,4.023809,2.670093,1.931252,4.448482
1,42,2,1,7,8,0,3470,11,11,1986,0,438650000,7612.89,57619.37976,113,23201066,240,96671.10833,2,59,0,0,0.0,0,0.0,0,0.0,120755,0,309216,10489,1328,0,3,2,2,0,1,0.666667,6.533145,2.499231,3.019493,1.399270,4.335986,21,320,1362,21,19,4,39.238095,7.974364,140701.447242,25959.585233,154231.435167,144059.477704,53.939891,33.509477,14.759094,-3,0.047,29.384662,0.038,0.045,333,0,44629.869276,182.434742,1.662570e+08,2510.731455,48701.681393,18.217840,187.546479,2.283223e+07,254.032348,91834.026291,0.000000,242360.642254,0.000000,5.068509,3.548384,2.467506,1.587749,4.071131,40725.102969,229.518102,1.940921e+08,3806.600763,44245.116035,31.333564,271.877668,2.935649e+07,277.134168,78607.926551,0.000000,287437.223218,0.000000,5.608225,4.222785,2.883093,1.945022,4.747559,53739.820320,104.266667,4.626383e+08,4801.333333,96091.755367,26.333333,186.733333,2.903000e+07,1442.057649,120755.000000,0.000000,309216.000000,0.000000,6.533145,2.499231,3.019493,1.399270,4.335986,50724.464178,164.072800,4.091667e+07,429.828685,17624.818421,2.335024,83.196306,3.416624e+06,220.008656,64477.336472,0.000000,214085.011590,0.000000,3.889478,3.714923,2.643469,0.963086,3.326727,52402.701262,160.326484,1.653230e+08,1722.625571,49717.365511,9.246575,82.751142,8.272968e+06,461.296022,81309.940639,0.000000,305442.808219,0.000000,5.207264,3.946431,3.647401,1.115555,4.408551,50108.594319,239.519231,1.181157e+08,1290.584615,43857.451243,7.357692,122.219231,7.717346e+06,333.219172,200760.196154,0.000000,216132.688462,0.000000,4.536364,4.198835,2.566916,1.579720,4.872755
2,78,1,2,18,4,3,1595,3,42,1994,1,613340000,17786.21,34484.01880,199,1687918516,34610,48769.67686,301,407,371,0,0.0,0,0.0,0,0.0,253330,0,165159,30581,2704,0,8,8,2,2,1,0.666667,2.265734,0.685633,1.106628,1.833608,2.839831,15,5659,3553,11,11,1,72.866667,23.191337,64715.839564,83080.341652,74449.615731,83069.250127,74.935159,42.805242,9.095648,-12,0.016,20.169689,0.016,0.031,189,0,35171.928027,245.471233,2.657397e+08,5741.705284,44279.017722,49.390998,414.180039,4.973183e+07,486.120865,61481.230137,0.000000,323437.272407,0.000000,5.659887,3.490074,3.150568,2.272588,5.257058,41286.309465,218.818389,1.770842e+08,3310.516500,47866.995252,26.746852,249.648285,4.677131e+07,383.161679,85574.482306,0.000000,282260.154472,0.000000,5.634353,3.769083,2.692437,1.911154,4.726214,32511.713706,171.636364,4.766587e+08,10247.000000,45747.191029,94.727273,399.727273,0.000000e+00,0.000000,210433.818182,0.000000,193286.454545,0.000000,3.096501,1.892693,1.115730,1.836681,3.127984,31226.586754,218.058221,2.900306e+08,6140.786308,30628.396982,57.154191,259.392194,1.657321e+07,278.448139,156349.654511,0.000000,208959.486244,0.000000,5.592588,0.721673,2.576660,2.143895,4.067558,32640.334288,182.613757,4.813406e+08,10349.536155,45433.926056,94.650794,461.689594,0.000000e+00,0.000000,240414.003527,0.000000,163120.816578,0.000000,2.188203,0.666448,1.068570,1.776886,2.793112,38386.178484,215.547458,2.051141e+08,4220.866016,43980.696790,33.438267,314.098923,3.084462e+07,317.416683,57279.348109,0.000000,280336.653143,0.000000,5.524240,4.023809,2.670093,1.931252,4.448482
3,35,2,1,5,4,0,2466,6,28,1957,15,488757600,9483.30,51538.76815,169,0,0,0.00000,0,0,0,0,0.0,0,0.0,0,0.0,49805,111,98604,293,58,0,11,11,1,0,1,1.000000,0.144510,5.921589,2.516764,0.500618,1.940400,56,227,2730,48,5,5,35.839286,18.444784,169607.758678,78663.619452,142872.849542,97885.206437,46.166352,24.522229,14.789971,-20,0.028,27.533977,0.102,0.154,3,1,34434.715836,235.380610,5.689525e+08,12210.005386,39370.958305,107.405745,627.689408,6.840171e+07,516.299514,59750.588869,5223.734291,308659.649910,2.226212,5.957390,4.494712,3.593691,2.163127,5.173140,39048.366166,220.194039,8.686774e+08,14859.765117,53109.757758,127.027229,632.083895,6.349719e+07,594.119614,68146.203483,4954.728076,319652.178094,1.617073,7.150050,3.750610,3.541528,2.132350,5.580070,51547.813869,159.833333,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,49805.000000,215.166667,98604.000000,2.833333,0.144510,5.921589,2.516764,0.500618,1.940400,49582.684663,118.746269,1.843964e+06,18.985075,8697.944523,0.179104,59.682836,0.000000e+00,0.000000,66749.108209,508.626866,185754.809701,1.910448,1.903302,4.116650,2.717738,0.669063,2.511798,51363.458134,142.921569,0.000000e+00,0.000000,0.000000,0.000000,3.176471,0.000000e+00,0.000000,54631.235294,248.784314,98202.588235,1.980392,0.567695,5.302866,2.522764,0.491388,1.985558,50032.941844,172.047619,3.770323e+07,413.023810,10485.232003,2.666667,23.642857,6.802143e+06,251.370382,52923.023810,383.952381,151100.857143,2.214286,1.145965,5.813568,2.913321,0.629005,2.632741
4,36,2,2,4,4,0,1255,2,44,2003,0,1088280000,37696.24,28869.72282,422,274032611,6796,40322.63258,62,775,0,2,138730.8,0,0.0,0,0.0,46725,0,928198,147575,13354,0,6,8,1,1,1,1.000000,8.763263,7.477743,8.133736,6.643515,13.817228,8,1156,486,3,7,1,56.250000,50.609852,104614.815020,88372.684692,77186.781252,117756.951718,77.491443,52.280512,7.267132,-1,0.005,46.504606,0.005,0.013,474,0,39513.500480,207.561170,2.136534e+08,4688.476064,42025.074616,38.579787,354.800532,4.054210e+07,455.194395,65265.109043,0.000000,300035.446809,0.000000,5.093770,4.190226,2.961413,1.981788,4.746594,40725.102969,229.518102,1.940921e+08,3806.600763,44245.116035,31.333564,271.877668,2.935649e+07,277.134168,78607.926551,0.000000,287437.223218,0.000000,5.608225,4.222785,2.883093,1.945022,4.747559,28328.723792,415.166667,4.905367e+08,12090.333333,40536.723585,132.333333,935.166667,2.151067e+08,2346.122474,46725.000000,0.000000,928198.000000,0.000000,8.763263,7.477743,8.133736,6.643515,13.817228,30064.657225,270.324324,4.455364e+08,10554.543184,42188.647757,100.215041,751.395417,1.125546e+08,970.094310,29897.245593,0.000000,532118.696240,0.000000,5.013983,4.044437,4.597562,3.693982,7.178049,29546.368987,338.152284,4.119331e+08,10093.155185,40797.245546,105.546773,995.436548,1.877803e+08,1642.630417,40552.019579,0.000000,779289.135606,0.000000,7.168547,6.210230,6.809382,5.475701,11.064850,44450.088562,215.379152,1.757185e+08,3045.600229,53401.176003,25.135166,284.792669,3.830074e+07,331.491458,72718.476518,0.000000,306993.166094,0.000000,6.077823,4.483336,3.140337,1.977003,4.938298

## log平滑

In [22]:
# 过大量级值取log平滑（针对线性模型有效）
# 连续变量做log计算
big_num_cols = ['totalTradeMoney','totalTradeArea','tradeMeanPrice','totalNewTradeMoney', 'totalNewTradeArea',
                'tradeNewMeanPrice','remainNewNum', 'supplyNewNum', 'supplyLandArea',
                'tradeLandArea','landTotalPrice','landMeanPrice','totalWorkers','newWorkers',
                'residentPopulation','pv','uv']
for col in big_num_cols:
        train[col] = train[col].map(lambda x: np.log1p(x))
        test[col] = test[col].map(lambda x: np.log1p(x))

In [23]:
#对比特征工程前后线性模型结果情况
test=test.fillna(0)
# Lasso回归
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=0.1)
lasso.fit(train,target_train)
#预测测试集和训练集结果
y_pred_train=lasso.predict(train)
y_pred_test=lasso.predict(test)

#对比结果
from sklearn.metrics import r2_score
score_train=r2_score(y_pred_train,target_train)
print("训练集结果：",score_train)
score_test=r2_score(y_pred_test, target_test)
print("测试集结果：",score_test)

训练集结果： -3.5292471822430898
测试集结果： -85652.22051941564

# 特征选择

In [24]:
# import pandas as pd
# import warnings
# warnings.filterwarnings('ignore')
# from sklearn.preprocessing import LabelEncoder
# #读取数据
# from sklearn.model_selection import train_test_split
# origin = pd.read_csv('数据集/train_data.csv')
# train, test, _, _ = train_test_split(origin, origin["tradeMoney"], test_size=0.3, random_state=30)
# target_train = train.pop('tradeMoney')
# target_test = test.pop('tradeMoney')

## 相关系数法

In [25]:
# 不同的算法进行特征选择

In [26]:
#相关系数法特征选择
from sklearn.feature_selection import SelectKBest

print(train.shape)

sk=SelectKBest(k=150)
new_train=sk.fit_transform(train,target_train)
print(new_train.shape)

# 获取对应列索引
select_columns=sk.get_support(indices = True)
# print(select_columns)

# 获取对应列名
# print(test.columns[select_columns])
select_columns_name=test.columns[select_columns]
new_test=test[select_columns_name]
print(new_test.shape)
# Lasso回归
from sklearn.linear_model import Lasso

lasso=Lasso(alpha=0.1)
lasso.fit(new_train,target_train)
#预测测试集和训练集结果
y_pred_train=lasso.predict(new_train)

y_pred_test=lasso.predict(new_test)

#对比结果
from sklearn.metrics import r2_score
score_train=r2_score(y_pred_train,target_train)
print("训练集结果：",score_train)
score_test=r2_score(y_pred_test, target_test)
print("测试集结果：",score_test)

(29008, 174)
(29008, 150)
(12432, 150)
训练集结果： -3.578462320492129
测试集结果： -91856.29302572335

## Wrapper

In [27]:
# Wrapper

from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
rfe = RFE(lr, n_features_to_select=160)
rfe.fit(train,target_train)

RFE(estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                               normalize=False),
    n_features_to_select=40, step=1, verbose=0)




select_columns = [f for f, s in zip(train.columns, rfe.support_) if s]
print(select_columns)
new_train = train[select_columns]
new_test = test[select_columns]

# Lasso回归
from sklearn.linear_model import Lasso

lasso=Lasso(alpha=0.1)
lasso.fit(new_train,target_train)
#预测测试集和训练集结果
y_pred_train=lasso.predict(new_train)

y_pred_test=lasso.predict(new_test)

#对比结果
from sklearn.metrics import r2_score
score_train=r2_score(y_pred_train,target_train)
print("训练集结果：",score_train)
score_test=r2_score(y_pred_test, target_test)
print("测试集结果：",score_test)

['area', 'rentType', 'houseFloor', 'totalFloor', 'houseToward', 'houseDecoration', 'communityName', 'region', 'plate', 'buildYear', 'saleSecHouseNum', 'totalTradeMoney', 'totalTradeArea', 'tradeMeanPrice', 'tradeSecNum', 'totalNewTradeMoney', 'totalNewTradeArea', 'tradeNewMeanPrice', 'tradeNewNum', 'remainNewNum', 'supplyNewNum', 'supplyLandNum', 'supplyLandArea', 'tradeLandNum', 'tradeLandArea', 'landTotalPrice', 'landMeanPrice', 'totalWorkers', 'newWorkers', 'residentPopulation', 'pv', 'uv', 'lookNum', 'month', 'day', 'Room', 'Hall', 'Bath', 'Room_Bath', 'trainsportNum', 'all_SchoolNum', 'all_hospitalNum', 'all_mall', 'otherNum', 'count_communityName', 'count_buildYear', 'count_totalFloor', 'count_communityName_totalFloor', 'count_communityName_newWorkers', 'count_communityName_totalTradeMoney', 'com_area_mean', 'com_area_std', 'comm_price_mean', 'plate_price_mean', 'plate_price_std', 'plate_area_mean', 'plate_area_std', 'plate_year_std', 'comm_plate_year_diff', 'trainsportNum_ratio', 'com_all_mall', 'other_ratio', 'sale_ratio', 'sale_newworker_differ', 'cluster', 'tradeMeanPrice_totalFloor_cluster_mean', 'tradeSecNum_totalFloor_cluster_mean', 'totalNewTradeArea_totalFloor_cluster_mean', 'tradeNewMeanPrice_totalFloor_cluster_mean', 'tradeNewNum_totalFloor_cluster_mean', 'remainNewNum_totalFloor_cluster_mean', 'landMeanPrice_totalFloor_cluster_mean', 'totalWorkers_totalFloor_cluster_mean', 'newWorkers_totalFloor_cluster_mean', 'residentPopulation_totalFloor_cluster_mean', 'lookNum_totalFloor_cluster_mean', 'trainsportNum_totalFloor_cluster_mean', 'all_SchoolNum_totalFloor_cluster_mean', 'all_hospitalNum_totalFloor_cluster_mean', 'all_mall_totalFloor_cluster_mean', 'otherNum_totalFloor_cluster_mean', 'tradeMeanPrice_houseDecoration_cluster_mean', 'tradeSecNum_houseDecoration_cluster_mean', 'totalNewTradeArea_houseDecoration_cluster_mean', 'tradeNewMeanPrice_houseDecoration_cluster_mean', 'tradeNewNum_houseDecoration_cluster_mean', 'remainNewNum_houseDecoration_cluster_mean', 'landMeanPrice_houseDecoration_cluster_mean', 'totalWorkers_houseDecoration_cluster_mean', 'newWorkers_houseDecoration_cluster_mean', 'residentPopulation_houseDecoration_cluster_mean', 'lookNum_houseDecoration_cluster_mean', 'trainsportNum_houseDecoration_cluster_mean', 'all_SchoolNum_houseDecoration_cluster_mean', 'all_hospitalNum_houseDecoration_cluster_mean', 'all_mall_houseDecoration_cluster_mean', 'otherNum_houseDecoration_cluster_mean', 'tradeMeanPrice_communityName_cluster_mean', 'tradeSecNum_communityName_cluster_mean', 'totalNewTradeArea_communityName_cluster_mean', 'tradeNewMeanPrice_communityName_cluster_mean', 'tradeNewNum_communityName_cluster_mean', 'remainNewNum_communityName_cluster_mean', 'landMeanPrice_communityName_cluster_mean', 'totalWorkers_communityName_cluster_mean', 'newWorkers_communityName_cluster_mean', 'residentPopulation_communityName_cluster_mean', 'lookNum_communityName_cluster_mean', 'trainsportNum_communityName_cluster_mean', 'all_SchoolNum_communityName_cluster_mean', 'all_hospitalNum_communityName_cluster_mean', 'all_mall_communityName_cluster_mean', 'otherNum_communityName_cluster_mean', 'tradeMeanPrice_region_cluster_mean', 'tradeSecNum_region_cluster_mean', 'totalNewTradeArea_region_cluster_mean', 'tradeNewMeanPrice_region_cluster_mean', 'tradeNewNum_region_cluster_mean', 'remainNewNum_region_cluster_mean', 'landMeanPrice_region_cluster_mean', 'totalWorkers_region_cluster_mean', 'newWorkers_region_cluster_mean', 'residentPopulation_region_cluster_mean', 'lookNum_region_cluster_mean', 'trainsportNum_region_cluster_mean', 'all_SchoolNum_region_cluster_mean', 'all_hospitalNum_region_cluster_mean', 'all_mall_region_cluster_mean', 'otherNum_region_cluster_mean', 'tradeMeanPrice_plate_cluster_mean', 'tradeSecNum_plate_cluster_mean', 'totalNewTradeArea_plate_cluster_mean', 'tradeNewMeanPrice_plate_cluster_mean', 'tradeNewNum_plate_cluster_mean', 'remainNewNum_plate_cluster_mean', 'landMeanPrice_plate_cluster_mean', 'totalWorkers_plate_cluster_mean', 'newWorkers_plate_cluster_mean', 'residentPopulation_plate_cluster_mean', 'lookNum_plate_cluster_mean', 'trainsportNum_plate_cluster_mean', 'all_SchoolNum_plate_cluster_mean', 'all_hospitalNum_plate_cluster_mean', 'all_mall_plate_cluster_mean', 'otherNum_plate_cluster_mean', 'tradeMeanPrice_buildYear_cluster_mean', 'tradeSecNum_buildYear_cluster_mean', 'totalNewTradeArea_buildYear_cluster_mean', 'tradeNewNum_buildYear_cluster_mean', 'remainNewNum_buildYear_cluster_mean', 'landMeanPrice_buildYear_cluster_mean', 'totalWorkers_buildYear_cluster_mean', 'newWorkers_buildYear_cluster_mean', 'residentPopulation_buildYear_cluster_mean', 'lookNum_buildYear_cluster_mean', 'trainsportNum_buildYear_cluster_mean', 'all_SchoolNum_buildYear_cluster_mean', 'all_hospitalNum_buildYear_cluster_mean', 'all_mall_buildYear_cluster_mean', 'otherNum_buildYear_cluster_mean']
训练集结果： -3.53908232168242
测试集结果： -86428.45340355093

## Embedded
### 基于惩罚项的特征选择法
### Lasso(l1)和Ridge(l2)

In [28]:
# Embedded
# 基于惩罚项的特征选择法
# Lasso(l1)和Ridge(l2)

from sklearn.linear_model import Ridge

ridge = Ridge(alpha=5)
ridge.fit(train,target_train)

Ridge(alpha=5, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)

# 特征系数排序
coefSort = ridge.coef_.argsort()
print(coefSort)


# 特征系数
featureCoefSore=ridge.coef_[coefSort]
print(featureCoefSore)


select_columns = [f for f, s in zip(train.columns, featureCoefSore) if abs(s)> 0.0000005 ] 
# 选择绝对值大于0.0000005的特征

new_train = train[select_columns]
new_test = test[select_columns]
# Lasso回归
from sklearn.linear_model import Lasso

lasso=Lasso(alpha=0.1)
lasso.fit(new_train,target_train)
#预测测试集和训练集结果
y_pred_train=lasso.predict(new_train)

y_pred_test=lasso.predict(new_test)

#对比结果
from sklearn.metrics import r2_score
score_train=r2_score(y_pred_train,target_train)
print("训练集结果：",score_train)
score_test=r2_score(y_pred_test, target_test)
print("测试集结果：",score_test)

[ 38 136  60  81  42 155  29  63  23  41 133  30  35  26  16  21 152  13
 150  78 151 114 134 173  17 115  58   9 170 119  28 143 116 161 169  51
  49  48  71  57  67  98 126  85 121  14 144  96 108 105 162  92 101  76
  66  93 123 110  74 124 148 131  77 129  46 113 167 111 165 147  53 160
  86 140 122  73 163 109 158  68 145 127  91 104  52 149 106 112  75  54
  55  64 142 102  70 146 156 138  95 120  45 166 128 100  69  72  94 164
 159  61  84   6 141 130  65  87  88  99 157  18  97  47 139   0 103  90
  25  44 125   5  34  89  22 107  79   2  10  19  33  50   3  56  20   4
  59  11  27  32 172   8  12  40  15 118 132 135  39 168 117  80 153   7
  83  31  24  82 171  36  43   1 154 137  62  37]
[-4.37637509e+03 -1.61645161e+03 -1.13777239e+03 -1.11710503e+03
 -1.07433944e+03 -9.15885783e+02 -7.63499983e+02 -7.09493705e+02
 -6.23313357e+02 -6.00180696e+02 -5.63264637e+02 -5.40593882e+02
 -4.72195970e+02 -4.70459457e+02 -3.90380349e+02 -3.67814456e+02
 -2.83311906e+02 -2.79249057e+02 -2.18579313e+02 -2.12011315e+02
 -2.06399621e+02 -1.86414282e+02 -1.72513731e+02 -1.15157842e+02
 -9.10429052e+01 -9.08886675e+01 -7.94085372e+01 -7.25356625e+01
 -5.04369719e+01 -3.01418334e+01 -2.22176430e+01 -1.86535598e+01
 -1.64269975e+01 -1.27143049e+01 -1.20649585e+01 -1.13628958e+01
 -1.06361229e+01 -8.51124224e+00 -4.58020186e+00 -3.52990493e+00
 -2.66076077e+00 -2.37677076e+00 -1.63135912e+00 -1.51139480e+00
 -1.41655223e+00 -1.36244136e+00 -1.04300038e+00 -4.50790448e-01
 -2.95299993e-01 -2.79451785e-01 -1.54529904e-01 -1.31205883e-01
 -1.24914449e-01 -9.93938733e-02 -6.74205375e-02 -5.18758608e-02
 -3.67358027e-02 -3.57262075e-02 -3.28887585e-02 -1.86405987e-02
 -1.58964923e-02 -1.30722114e-02 -8.88158406e-03 -5.98468770e-03
 -5.61372422e-03 -4.54493115e-03 -3.28602054e-03 -2.36943576e-03
 -2.26857466e-03 -2.17496749e-03 -1.17092622e-03 -4.18708652e-04
 -2.01625164e-05 -1.59067338e-06 -1.31772019e-06 -1.06150564e-06
 -6.13720517e-07 -4.97433024e-07  2.76962911e-08  7.84043778e-08
  1.25720331e-07  1.03411338e-06  1.45801129e-06  2.16772553e-06
  1.81204516e-03  2.21600993e-03  2.44393413e-03  3.76299412e-03
  4.27847958e-03  6.00772069e-03  1.06299931e-02  1.06315088e-02
  1.07685137e-02  1.27031864e-02  1.44046122e-02  1.91938830e-02
  1.92912539e-02  2.05792844e-02  2.39880635e-02  2.54081011e-02
  2.99087012e-02  3.78742072e-02  4.56410535e-02  7.00845853e-02
  9.34922696e-02  1.03259516e-01  1.73504592e-01  1.74804204e-01
  1.93841879e-01  2.19115734e-01  2.29560331e-01  2.35409399e-01
  2.56221181e-01  2.79090999e-01  3.54739139e-01  3.63396371e-01
  3.72514903e-01  5.93424618e-01  1.19608859e+00  1.22519156e+00
  1.76180667e+00  2.05200499e+00  2.50609801e+00  2.64518071e+00
  2.67991841e+00  3.58250275e+00  3.68699932e+00  5.22682286e+00
  5.26755708e+00  6.53481700e+00  1.01712728e+01  1.48656708e+01
  1.51868764e+01  1.80960644e+01  1.83294126e+01  2.52692014e+01
  2.76100392e+01  2.90081189e+01  3.22346113e+01  3.45063483e+01
  3.83734786e+01  5.91355501e+01  6.34662402e+01  7.70524710e+01
  7.71784564e+01  8.96023981e+01  9.34311556e+01  1.28119480e+02
  1.40869526e+02  1.43941987e+02  1.64234505e+02  1.78219548e+02
  2.07998882e+02  2.59944470e+02  2.92861981e+02  3.00801307e+02
  3.18214165e+02  3.73222906e+02  3.82268718e+02  3.90890777e+02
  4.02535542e+02  4.36418731e+02  4.49339055e+02  4.53793399e+02
  4.68293672e+02  4.94193310e+02  5.40156814e+02  5.71983486e+02
  7.58441766e+02  1.32727156e+03  1.82530490e+03  1.93354764e+03
  2.21533873e+03  4.01089344e+03]
训练集结果： -3.5404747502831535
测试集结果： -85805.85150006511

### 基于树模型的特征选择法
### 随机森林 平均不纯度减少（mean decrease impurity

In [29]:
# Embedded
# 基于树模型的特征选择法
# 随机森林 平均不纯度减少（mean decrease impurity


from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
# 训练随机森林模型，并通过feature_importances_属性获取每个特征的重要性分数。rf = RandomForestRegressor()
rf.fit(train,target_train)
print("Features sorted by their score:")
print(sorted(zip(map(lambda x: round(x, 4), rf.feature_importances_), train.columns),
             reverse=True))

select_columns = [f for f, s in zip(train.columns, rf.feature_importances_) if abs(s)> 0.00005 ] 
# 选择绝对值大于0.00005的特征

new_train = train[select_columns]
new_test = test[select_columns]

# Lasso回归
from sklearn.linear_model import Lasso

lasso=Lasso(alpha=0.1)
lasso.fit(new_train,target_train)
#预测测试集和训练集结果
y_pred_train=lasso.predict(new_train)

y_pred_test=lasso.predict(new_test)

#对比结果
from sklearn.metrics import r2_score
score_train=r2_score(y_pred_train,target_train)
print("训练集结果：",score_train)
score_test=r2_score(y_pred_test, target_test)
print("测试集结果：",score_test)

Features sorted by their score:
[(0.2269, 'area'), (0.0648, 'day'), (0.0479, 'pv'), (0.0442, 'saleSecHouseNum'), (0.0408, 'tradeMeanPrice'), (0.0392, 'houseFloor'), (0.0377, 'Hall'), (0.0281, 'all_mall_buildYear_cluster_mean'), (0.0248, 'buildYear'), (0.02, 'sale_newworker_differ'), (0.019, 'landMeanPrice'), (0.0185, 'totalTradeMoney'), (0.0178, 'landMeanPrice_buildYear_cluster_mean'), (0.0165, 'tradeNewNum_communityName_cluster_mean'), (0.0146, 'totalWorkers_buildYear_cluster_mean'), (0.0141, 'all_SchoolNum_buildYear_cluster_mean'), (0.014, 'lookNum'), (0.0132, 'supplyNewNum'), (0.0132, 'landTotalPrice_totalFloor_cluster_mean'), (0.0118, 'uv'), (0.0114, 'sale_ratio'), (0.0109, 'totalWorkers'), (0.0101, 'remainNewNum_communityName_cluster_mean'), (0.0099, 'tradeNewMeanPrice_communityName_cluster_mean'), (0.0099, 'supplyLandNum'), (0.0098, 'tradeLandArea'), (0.0096, 'otherNum_totalFloor_cluster_mean'), (0.0093, 'comm_plate_year_diff'), (0.0086, 'remainNewNum_buildYear_cluster_mean'), (0.0085, 'trainsportNum_buildYear_cluster_mean'), (0.0082, 'Room_Bath'), (0.0081, 'tradeNewNum'), (0.0079, 'count_totalFloor'), (0.0078, 'tradeMeanPrice_communityName_cluster_mean'), (0.0078, 'plate'), (0.0078, 'com_area_std'), (0.0074, 'totalNewTradeMoney'), (0.0071, 'all_SchoolNum_communityName_cluster_mean'), (0.007, 'count_communityName_newWorkers'), (0.0067, 'all_SchoolNum_plate_cluster_mean'), (0.0065, 'newWorkers_buildYear_cluster_mean'), (0.0059, 'totalNewTradeMoney_buildYear_cluster_mean'), (0.0058, 'all_mall_totalFloor_cluster_mean'), (0.0055, 'count_communityName'), (0.0055, 'com_area_mean'), (0.0049, 'totalTradeArea'), (0.0046, 'tradeNewMeanPrice'), (0.0043, 'tradeMeanPrice_plate_cluster_mean'), (0.0032, 'plate_area_mean'), (0.0031, 'trainsportNum_totalFloor_cluster_mean'), (0.0024, 'otherNum_buildYear_cluster_mean'), (0.0021, 'trainsportNum_communityName_cluster_mean'), (0.0021, 'comm_price_mean'), (0.002, 'trainsportNum_ratio'), (0.0019, 'plate_year_std'), (0.0018, 'totalFloor'), (0.0017, 'lookNum_region_cluster_mean'), (0.0016, 'plate_area_std'), (0.0012, 'tradeMeanPrice_totalFloor_cluster_mean'), (0.0011, 'tradeNewMeanPrice_region_cluster_mean'), (0.0011, 'communityName'), (0.0011, 'comm_price_std'), (0.001, 'tradeNewMeanPrice_plate_cluster_mean'), (0.001, 'residentPopulation_buildYear_cluster_mean'), (0.001, 'remainNewNum'), (0.001, 'otherNum_communityName_cluster_mean'), (0.001, 'com_all_mall'), (0.0009, 'tradeNewMeanPrice_totalFloor_cluster_mean'), (0.0009, 'all_SchoolNum'), (0.0008, 'tradeSecNum_communityName_cluster_mean'), (0.0008, 'tradeMeanPrice_region_cluster_mean'), (0.0007, 'totalWorkers_plate_cluster_mean'), (0.0007, 'other_ratio'), (0.0007, 'all_SchoolNum_totalFloor_cluster_mean'), (0.0007, 'Bath'), (0.0006, 'tradeSecNum_region_cluster_mean'), (0.0006, 'tradeNewMeanPrice_buildYear_cluster_mean'), (0.0006, 'landTotalPrice_buildYear_cluster_mean'), (0.0006, 'Room'), (0.0005, 'tradeSecNum'), (0.0005, 'tradeMeanPrice_buildYear_cluster_mean'), (0.0005, 'totalWorkers_totalFloor_cluster_mean'), (0.0005, 'residentPopulation'), (0.0004, 'totalWorkers_communityName_cluster_mean'), (0.0004, 'residentPopulation_totalFloor_cluster_mean'), (0.0004, 'residentPopulation_communityName_cluster_mean'), (0.0004, 'remainNewNum_plate_cluster_mean'), (0.0004, 'otherNum'), (0.0004, 'month'), (0.0004, 'houseToward'), (0.0004, 'count_communityName_totalFloor'), (0.0004, 'count_buildYear'), (0.0004, 'all_hospitalNum_plate_cluster_mean'), (0.0004, 'all_hospitalNum_communityName_cluster_mean'), (0.0003, 'tradeSecNum_totalFloor_cluster_mean'), (0.0003, 'tradeSecNum_plate_cluster_mean'), (0.0003, 'tradeNewNum_plate_cluster_mean'), (0.0003, 'tradeNewNum_buildYear_cluster_mean'), (0.0003, 'totalWorkers_houseDecoration_cluster_mean'), (0.0003, 'totalNewTradeArea'), (0.0003, 'residentPopulation_plate_cluster_mean'), (0.0003, 'plate_price_std'), (0.0003, 'all_mall'), (0.0003, 'all_hospitalNum_totalFloor_cluster_mean'), (0.0003, 'all_hospitalNum_buildYear_cluster_mean'), (0.0003, 'all_hospitalNum'), (0.0002, 'trainsportNum_plate_cluster_mean'), (0.0002, 'trainsportNum_houseDecoration_cluster_mean'), (0.0002, 'tradeSecNum_buildYear_cluster_mean'), (0.0002, 'totalNewTradeMoney_totalFloor_cluster_mean'), (0.0002, 'totalNewTradeMoney_plate_cluster_mean'), (0.0002, 'totalNewTradeMoney_communityName_cluster_mean'), (0.0002, 'totalNewTradeArea_region_cluster_mean'), (0.0002, 'totalNewTradeArea_communityName_cluster_mean'), (0.0002, 'totalNewTradeArea_buildYear_cluster_mean'), (0.0002, 'rentType'), (0.0002, 'plate_price_mean'), (0.0002, 'otherNum_plate_cluster_mean'), (0.0002, 'lookNum_totalFloor_cluster_mean'), (0.0002, 'landTotalPrice_communityName_cluster_mean'), (0.0002, 'landMeanPrice_totalFloor_cluster_mean'), (0.0002, 'landMeanPrice_houseDecoration_cluster_mean'), (0.0002, 'count_communityName_totalTradeMoney'), (0.0002, 'all_mall_plate_cluster_mean'), (0.0002, 'all_mall_communityName_cluster_mean'), (0.0002, 'all_SchoolNum_region_cluster_mean'), (0.0001, 'trainsportNum_region_cluster_mean'), (0.0001, 'trainsportNum'), (0.0001, 'tradeSecNum_houseDecoration_cluster_mean'), (0.0001, 'tradeNewNum_totalFloor_cluster_mean'), (0.0001, 'tradeNewMeanPrice_houseDecoration_cluster_mean'), (0.0001, 'totalNewTradeArea_totalFloor_cluster_mean'), (0.0001, 'residentPopulation_region_cluster_mean'), (0.0001, 'remainNewNum_totalFloor_cluster_mean'), (0.0001, 'remainNewNum_region_cluster_mean'), (0.0001, 'otherNum_region_cluster_mean'), (0.0001, 'newWorkers_totalFloor_cluster_mean'), (0.0001, 'newWorkers_houseDecoration_cluster_mean'), (0.0001, 'newWorkers_communityName_cluster_mean'), (0.0001, 'lookNum_plate_cluster_mean'), (0.0001, 'all_SchoolNum_houseDecoration_cluster_mean'), (0.0, 'tradeNewNum_region_cluster_mean'), (0.0, 'tradeNewNum_houseDecoration_cluster_mean'), (0.0, 'tradeMeanPrice_houseDecoration_cluster_mean'), (0.0, 'tradeLandNum'), (0.0, 'totalWorkers_region_cluster_mean'), (0.0, 'totalNewTradeMoney_region_cluster_mean'), (0.0, 'totalNewTradeMoney_houseDecoration_cluster_mean'), (0.0, 'totalNewTradeArea_plate_cluster_mean'), (0.0, 'totalNewTradeArea_houseDecoration_cluster_mean'), (0.0, 'supplyLandArea'), (0.0, 'residentPopulation_houseDecoration_cluster_mean'), (0.0, 'remainNewNum_houseDecoration_cluster_mean'), (0.0, 'region'), (0.0, 'otherNum_houseDecoration_cluster_mean'), (0.0, 'newWorkers_region_cluster_mean'), (0.0, 'newWorkers_plate_cluster_mean'), (0.0, 'newWorkers'), (0.0, 'lookNum_houseDecoration_cluster_mean'), (0.0, 'lookNum_communityName_cluster_mean'), (0.0, 'lookNum_buildYear_cluster_mean'), (0.0, 'landTotalPrice_region_cluster_mean'), (0.0, 'landTotalPrice_plate_cluster_mean'), (0.0, 'landTotalPrice_houseDecoration_cluster_mean'), (0.0, 'landTotalPrice'), (0.0, 'landMeanPrice_region_cluster_mean'), (0.0, 'landMeanPrice_plate_cluster_mean'), (0.0, 'landMeanPrice_communityName_cluster_mean'), (0.0, 'houseDecoration'), (0.0, 'cluster'), (0.0, 'all_mall_region_cluster_mean'), (0.0, 'all_mall_houseDecoration_cluster_mean'), (0.0, 'all_hospitalNum_region_cluster_mean'), (0.0, 'all_hospitalNum_houseDecoration_cluster_mean')]
训练集结果： -3.577462964959568
测试集结果： -89092.31190317847

In [30]:
X_train = train
X_test = test
Y_train = target_train
Y_test = target_test

In [33]:
X_test.to_csv("X_test.csv")
Y_test.to_csv("Y_test.csv")

In [ ]:
print(X_train.shape)

In [ ]:
X_train.head()

In [ ]:
# from __future__ import print_function
# import pandas as pd
# import lightgbm as lgb
# import sklearn
# import numpy
# import hyperopt
# from hyperopt import hp, fmin, tpe, STATUS_OK, Trials
# import colorama
# import numpy as np
# from sklearn.model_selection import KFold
# from sklearn.model_selection import train_test_split


# N_HYPEROPT_PROBES = 500
# HYPEROPT_ALGO = tpe.suggest  #  tpe.suggest OR hyperopt.rand.suggest

# # ----------------------------------------------------------

# colorama.init()

# # ---------------------------------------------------------------------

# def get_lgb_params(space):
#     lgb_params = dict()
#     lgb_params['boosting_type'] = space['boosting_type'] if 'boosting_type' in space else 'gbdt'
#     lgb_params['objective'] = 'regression'
#     lgb_params['metric'] = 'rmse'
#     lgb_params['learning_rate'] = space['learning_rate']
#     lgb_params['num_leaves'] = int(space['num_leaves'])
#     lgb_params['min_data_in_leaf'] = int(space['min_data_in_leaf'])
#     lgb_params['min_sum_hessian_in_leaf'] = space['min_sum_hessian_in_leaf']
#     lgb_params['max_depth'] = -1
#     lgb_params['lambda_l1'] = space['lambda_l1'] if 'lambda_l1' in space else 0.0
#     lgb_params['lambda_l2'] = space['lambda_l2'] if 'lambda_l2' in space else 0.0
#     lgb_params['max_bin'] = int(space['max_bin']) if 'max_bin' in space else 256
#     lgb_params['feature_fraction'] = space['feature_fraction']
#     lgb_params['bagging_fraction'] = space['bagging_fraction']
#     lgb_params['bagging_freq'] = int(space['bagging_freq']) if 'bagging_freq' in space else 1
#     lgb_params['nthread'] = 4
#     return lgb_params

# # ---------------------------------------------------------------------

# obj_call_count = 0
# cur_best_score = 0 # 0 or np.inf
# log_writer = open( 'log/lgb-hyperopt-log.txt', 'w' )


# def objective(space):
#     global obj_call_count, cur_best_score

#     obj_call_count += 1

#     print('\nLightGBM objective call #{} cur_best_score={:7.5f}'.format(obj_call_count,cur_best_score) )

#     lgb_params = get_lgb_params(space)

#     sorted_params = sorted(space.items(), key=lambda z: z[0])
#     params_str = str.join(' ', ['{}={}'.format(k, v) for k, v in sorted_params])
#     print('Params: {}'.format(params_str) )
    
#     kf = KFold(n_splits=3, shuffle=True, random_state=0)
#     out_of_fold = np.zeros(len(X_train))
#     for fold, (train_idx, val_idx) in enumerate(kf.split(X_train)):
#         D_train = lgb.Dataset(X_train.iloc[train_idx], label=Y_train[train_idx])
#         D_val = lgb.Dataset(X_train.iloc[val_idx], label=Y_train[val_idx])
#         # Train
#         num_round = 10000
#         clf = lgb.train(lgb_params,
#                            D_train,
#                            num_boost_round=num_round,
#                            # metrics='mlogloss',
#                            valid_sets=D_val,
#                            # valid_names='val',
#                            # fobj=None,
#                            # feval=None,
#                            # init_model=None,
#                            # feature_name='auto',
#                            # categorical_feature='auto',
#                            early_stopping_rounds=200,
#                            # evals_result=None,
#                            verbose_eval=False,
#                            # learning_rates=None,
#                            # keep_training_booster=False,
#                            # callbacks=None
#                            )
#         # predict
#         nb_trees = clf.best_iteration
#         val_loss = clf.best_score['valid_0']
#         print('nb_trees={} val_loss={}'.format(nb_trees, val_loss))
#         out_of_fold[val_idx] = clf.predict(X_train.iloc[val_idx], num_iteration=nb_trees)
#         score = r2_score(out_of_fold, Y_train)

#     print('val_r2_score={}'.format(score))

#     log_writer.write('score={} Params:{} nb_trees={}\n'.format(score, params_str, nb_trees ))
#     log_writer.flush()

#     if score>cur_best_score:
#         cur_best_score = score
#         print(colorama.Fore.GREEN + 'NEW BEST SCORE={}'.format(cur_best_score) + colorama.Fore.RESET)
#     return {'loss': -score, 'status': STATUS_OK}

# # --------------------------------------------------------------------------------

# space ={
#         'num_leaves': hp.quniform ('num_leaves', 10, 100, 1),
#         'min_data_in_leaf':  hp.quniform ('min_data_in_leaf', 10, 100, 1),
#         'feature_fraction': hp.uniform('feature_fraction', 0.75, 1.0),
#         'bagging_fraction': hp.uniform('bagging_fraction', 0.75, 1.0),
#         'learning_rate': hp.uniform('learning_rate', 0, 0.01),
# #         'learning_rate': hp.loguniform('learning_rate', -5.0, -2.3),
#         'min_sum_hessian_in_leaf': hp.loguniform('min_sum_hessian_in_leaf', 0, 2.3),
#         'max_bin': hp.quniform ('max_bin', 88, 200, 1),
#         'bagging_freq': hp.quniform ('bagging_freq', 1, 15, 1),
#         'lambda_l1': hp.uniform('lambda_l1', 0, 10 ),
#         'lambda_l2': hp.uniform('lambda_l2', 0, 10 ),
#        }

# trials = Trials()
# best = hyperopt.fmin(fn=objective,
#                      space=space,
#                      algo=HYPEROPT_ALGO,
#                      max_evals=N_HYPEROPT_PROBES,
#                      trials=trials,
#                      verbose=1)

# print('-'*50)
# print('The best params:')
# print( best )
# print('\n\n')

# 模型融合

In [ ]:
# params = {'lambda_l1': 5.685586861084649, 'learning_rate': 0.008598433947258264, 'bagging_freq': 13.0,
#           'min_sum_hessian_in_leaf': 1.2350791010411553, 'bagging_fraction': 0.9639298153601001,
#           'feature_fraction': 0.9594875893508883, 'min_data_in_leaf': 10.0, 'num_leaves': 65.0,
#           'max_bin': 175.0, 'lambda_l2': 3.434787804152256}
# params["num_leaves"] = int(params["num_leaves"])
# params["bagging_freq"] = int(params["bagging_freq"])
# params["min_data_in_leaf"] = int(params["min_data_in_leaf"])
# params["max_bin"] = int(params["max_bin"])

In [ ]:
# X_train = pd.read_csv("X_train.csv")
# Y_train = pd.read_csv("Y_train.csv")
# X_train = X_train.drop(["Unnamed: 0"], axis=1)
# Y_train = Y_train.drop(["Unnamed: 0"], axis=1)
# print(X_train.shape)
# print(Y_train.shape)

# categorical_feats = ['rentType', 'houseFloor', 'houseToward', 'houseDecoration',  'region', 'plate','cluster']

In [ ]:
# feature = X_train
# label = Y_train

In [ ]:

# folds = KFold(n_splits=5, shuffle=True, random_state=2333)

# "===================================第一轮========================================================"
# y_pre_list = []
# r2_list = []
# train_feat = pd.Series()
# for fold_, (trn_idx, val_idx) in enumerate(folds.split(feature.values, label)):
#     print("fold {}".format(fold_))
#     trn_data = lgb.Dataset(feature.iloc[trn_idx], label.iloc[trn_idx], categorical_feature=categorical_feats)
#     val_data = lgb.Dataset(feature.iloc[val_idx], label.iloc[val_idx], categorical_feature=categorical_feats)

#     num_round = 10000
#     clf = lgb.train(params, trn_data, num_round,valid_sets=[trn_data, val_data], verbose_eval=500,
#                 early_stopping_rounds=200)
#     y_pre = clf.predict(feature.iloc[val_idx], num_iteration=clf.best_iteration)
#     r2 = r2_score(y_pre,label[val_idx])
#     r2_list.append(r2)
#     train_feat = train_feat.append(pd.Series(y_pre,index=val_idx))
#     y_pre_test = clf.predict(test,num_iteration=clf.best_iteration)
#     y_pre_list.append(y_pre_test)
# print('r2 score{:}'.format(r2))
# print('r2:{:}'.format(np.mean(r2_list)))

# y_pred_final=  (y_pre_list[0]+y_pre_list[1]+y_pre_list[2]+y_pre_list[3]+y_pre_list[4])/5
# feature['pre'] = train_feat
# test['pre'] = y_pred_final
# "===================================第二轮========================================================"
# y_pre_list = []
# r2_list = []
# train_feat = pd.Series()
# for fold_, (trn_idx, val_idx) in enumerate(folds.split(feature.values, label)):
#     print("fold {}".format(fold_))
#     trn_data = lgb.Dataset(feature.iloc[trn_idx], label[trn_idx], categorical_feature=categorical_feats)
#     val_data = lgb.Dataset(feature.iloc[val_idx], label[val_idx], categorical_feature=categorical_feats)

#     num_round = 10000
#     clf = lgb.train(params, trn_data, num_round, feval=get_r2_metric,valid_sets=[trn_data, val_data], verbose_eval=500,
#                 early_stopping_rounds=200)
#     y_pre = clf.predict(feature.iloc[val_idx], num_iteration=clf.best_iteration)
#     r2 = r2_score(y_pre,label[val_idx])
#     r2_list.append(r2)
#     train_feat = train_feat.append(pd.Series(y_pre,index=val_idx))
#     y_pre_test = clf.predict(test,num_iteration=clf.best_iteration)
#     y_pre_list.append(y_pre_test)
# print('r2 score{:}'.format(r2))
# print('r2:{:}'.format(np.mean(r2_list)))

# y_pred_final=  (y_pre_list[0]+y_pre_list[1]+y_pre_list[2]+y_pre_list[3]+y_pre_list[4])/5
# feature['pre_2'] = train_feat
# test['pre_2'] = y_pred_final
# "=======================第三轮========================================================"
# y_pre_list = []
# r2_list = []
# train_feat = pd.Series()
# for fold_, (trn_idx, val_idx) in enumerate(folds.split(feature.values, label)):
#     print("fold {}".format(fold_))
#     trn_data = lgb.Dataset(feature.iloc[trn_idx], label[trn_idx], categorical_feature=categorical_feats)
#     val_data = lgb.Dataset(feature.iloc[val_idx], label[val_idx], categorical_feature=categorical_feats)

#     num_round = 10000
#     clf = lgb.train(params, trn_data, num_round, feval=get_r2_metric,valid_sets=[trn_data, val_data], verbose_eval=500,
#                 early_stopping_rounds=200)
#     y_pre = clf.predict(feature.iloc[val_idx], num_iteration=clf.best_iteration)
#     r2 = r2_score(y_pre,label[val_idx])
#     r2_list.append(r2)
#     train_feat = train_feat.append(pd.Series(y_pre,index=val_idx))
#     y_pre_test = clf.predict(test,num_iteration=clf.best_iteration)
#     y_pre_list.append(y_pre_test)
# print('r2 score{:}'.format(r2))
# print('r2:{:}'.format(np.mean(r2_list)))

# y_pred_final=  (y_pre_list[0]+y_pre_list[1]+y_pre_list[2]+y_pre_list[3]+y_pre_list[4])/5

# #     return y_pred_final